# Default values for kubizone cloudflare integration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

logLevel: DEBUG

image:
  repository: ghcr.io/kubi-zone/kubizone-externaldns
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
args: ["reconcile"]

# Endpoint the sidecar will be exposed on.
webhookEndpoint: null
# webhookEndpoint: "http://localhost:8888"

# sidecars:
#   - name: hetzner-webhook
#     image: ghcr.io/mconfalonieri/external-dns-hetzner-webhook:v0.6.0
#     ports:
#       - containerPort: 8888
#         name: webhook
#       - containerPort: 8080
#         name: http
#     livenessProbe:
#       httpGet:
#         path: /health
#         port: http
#       initialDelaySeconds: 10
#       timeoutSeconds: 5
#     readinessProbe:
#       httpGet:
#         path: /ready
#         port: http
#       initialDelaySeconds: 10
#       timeoutSeconds: 5
#     env:
#       - name: HETZNER_API_KEY
#         valueFrom:
#           secretKeyRef:
#             name: hetzner-credentials
#             key: api-key
#     securityContext:
#       allowPrivilegeEscalation: false
#       capabilities:
#         drop:
#           - ALL
#       readOnlyRootFilesystem: true
#       runAsNonRoot: true
#       runAsUser: 65203

imagePullSecrets: []
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext:
  seccompProfile:
    type: "RuntimeDefault"
  runAsNonRoot: true
  runAsUser: 65203
  runAsGroup: 65203
  fsGroup: 65203
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65203
resources:
  limits:
    cpu: 20m
    memory: 32Mi
  requests:
    cpu: 5m
    memory: 16Mi
nodeSelector: {}
tolerations: []
affinity: {}
