{{- if .Values.apiKey.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}-cf-token
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.apiKey.token }}
{{- end }}